<?xml version="1.0"?>
<robot name="robo_bot" xmlns:xacro="http://ros.org/wiki/xacro">

  <material name="black">
    <color rgba="0.0 0.0 0.0 1.0"/>
  </material>

  <!-- Robot Parameters -->
  <xacro:property name="wheel_radius" value="0.1"/>
  <xacro:property name="wheel_width" value="0.02"/>
  <xacro:property name="base_length" value="0.4"/>
  <xacro:property name="base_width" value="0.4"/>
  <xacro:property name="base_height" value="0.25"/>
  <xacro:property name="clearance" value="0.00"/>

  <!-- Base Link -->
  <link name="base">
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <origin xyz="0 0 ${wheel_radius + clearance + base_height/2}" rpy="0 0 0"/>
      <material name="gray">
        <color rgba="0.7 0.7 0.7 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <origin xyz="0 0 ${wheel_radius + clearance + base_height/2}" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="0.5"/>
      <origin xyz="0 0 ${wheel_radius + clearance + base_height/2}" rpy="0 0 0"/>
      <inertia ixx="0.01" iyy="0.01" izz="0.01" ixy="0.0" ixz="0.0" iyz="0.0"/>
    </inertial>
  </link>

<xacro:macro name="wheel" params="name x_pos y_pos mimic_joint=''" >
  <link name="${name}">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
    </collision>
    <inertial>
      <mass value="0.5"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia 
        ixx="0.0001875" 
        iyy="0.0001875" 
        izz="0.000625"
        ixy="0.0" 
        ixz="0.0" 
        iyz="0.0"/>
    </inertial>
  </link>

  <gazebo reference="${name}">
    <mu1>0.1</mu1>
    <mu2>0.1</mu2>
    <kp>100000.0</kp>
    <kd>1.0</kd>
    <material>Gazebo/Black</material>
  </gazebo>

  <joint name="${name}_joint" type="continuous">
    <parent link="base"/>
    <child link="${name}"/>
    <origin xyz="${x_pos} ${y_pos} ${wheel_radius}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="100.0" velocity="5.0"/>
    <dynamics damping="0.0" friction="0.0"/>
    <xacro:if value="${mimic_joint != ''}">
      <mimic joint="${mimic_joint}" multiplier="1"/>
    </xacro:if>
  </joint>
</xacro:macro>

<!-- Front wheels mimic rear wheels -->
<xacro:wheel name="wheel_fl" x_pos="${ base_length/2 - wheel_radius }" y_pos="${  base_width/2 + wheel_width/2 }" mimic_joint="wheel_rl_joint"/>
<xacro:wheel name="wheel_fr" x_pos="${ base_length/2 - wheel_radius }" y_pos="${ -base_width/2 - wheel_width/2 }" mimic_joint="wheel_rr_joint"/>

<!-- Rear wheels are driven -->
<xacro:wheel name="wheel_rl" x_pos="${-base_length/2 + wheel_radius }" y_pos="${  base_width/2 + wheel_width/2 }"/>
<xacro:wheel name="wheel_rr" x_pos="${-base_length/2 + wheel_radius }" y_pos="${ -base_width/2 - wheel_width/2 }"/>


  <!-- Differential Drive Plugin -->
  <gazebo>
    <plugin name="diff_drive_controller_rear" filename="libgazebo_ros_diff_drive.so">
      <ros>
        <remapping>cmd_vel:=/cmd_vel</remapping>
      </ros>
      <left_joint>wheel_rl_joint</left_joint>
      <right_joint>wheel_rr_joint</right_joint>
      <wheel_separation>${base_width}</wheel_separation>
      <wheel_radius>${wheel_radius}</wheel_radius>
      <max_wheel_torque>1.0</max_wheel_torque>
      <max_wheel_speed>5.0</max_wheel_speed>
      <command_topic>/cmd_vel</command_topic>
      <odometry_topic>/odom</odometry_topic>
      <odometry_frame>odom</odometry_frame>
      <robot_base_frame>base</robot_base_frame>
      <publish_odom>true</publish_odom>
      <publish_tf>true</publish_tf>
    </plugin>
  </gazebo>

  <gazebo>
    <plugin name="diff_drive_controller_front" filename="libgazebo_ros_diff_drive.so">
      <ros>
        <remapping>cmd_vel:=/cmd_vel</remapping>
      </ros>
      <left_joint>wheel_fl_joint</left_joint>
      <right_joint>wheel_fr_joint</right_joint>
      <wheel_separation>${base_width}</wheel_separation>
      <wheel_radius>${wheel_radius}</wheel_radius>
      <max_wheel_torque>1.0</max_wheel_torque>
      <max_wheel_speed>5.0</max_wheel_speed>
      <command_topic>/cmd_vel</command_topic>
      <odometry_topic>/odom</odometry_topic>
      <odometry_frame>odom</odometry_frame>
      <robot_base_frame>base</robot_base_frame>
      <publish_odom>true</publish_odom>
      <publish_tf>true</publish_tf>
    </plugin>
  </gazebo>

   <!-- LIDAR -->
  <link name="lidar_link">
    <visual>
      <geometry>
        <cylinder radius="0.05" length="0.02"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="black">
        <color rgba="0.0 0.0 0.0 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="0.05" length="0.02"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.0001" iyy="0.0001" izz="0.0001" ixy="0.0" ixz="0.0" iyz="0.0"/>
    </inertial>
  </link>

  <joint name="lidar_joint" type="fixed">
    <parent link="base"/>
    <child link="lidar_link"/>
    <origin xyz="0 0 ${wheel_radius + clearance + base_height + 0.05}" rpy="0 0 0"/>
  </joint>

  <gazebo reference="lidar_link">
    <sensor name="lidar_sensor" type="ray">
      <pose>0 0 0 0 0 0</pose>
      <update_rate>30</update_rate>
      <visualize>true</visualize>
      <ray>
        <scan>
          <horizontal>
            <samples>360</samples>
            <resolution>1</resolution>
            <min_angle>-3.14</min_angle>
            <max_angle>3.14</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.1</min>
          <max>10.0</max>
          <resolution>0.01</resolution>
        </range>
      </ray>
      <plugin name="gazebo_ros_laser" filename="libgazebo_ros_ray_sensor.so">
        <frame_name>lidar_link</frame_name>
        <output_type>sensor_msgs/LaserScan</output_type>
      </plugin>
    </sensor>
  </gazebo>

  <!-- Camera -->
  <link name="camera_link">
    <visual>
      <geometry>
        <box size="0.05 0.05 0.05"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="black">
        <color rgba="0.2 0.2 0.2 1.0"/>
      </material>
    </visual>
  </link>

  <joint name="camera_joint" type="fixed">
    <parent link="base"/>
    <child link="camera_link"/>
    <origin xyz="${base_length/2 + 0.025} 0 ${wheel_radius + clearance + base_height/2}" rpy="0 0 0"/>
  </joint>

  <gazebo reference="camera_link">
    <sensor name="camera" type="camera">
      <always_on>true</always_on>
      <update_rate>30.0</update_rate>
      <visualize>true</visualize>
      <camera>
        <horizontal_fov>1.047</horizontal_fov>
        <image>
          <width>640</width>
          <height>480</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.1</near>
          <far>100.0</far>
        </clip>
      </camera>
      <plugin name="gazebo_ros_camera" filename="libgazebo_ros_camera.so">
        <ros>
          <remapping>image_raw:=/camera/image_raw</remapping>
        </ros>
        <camera_name>front_camera</camera_name>
        <frame_name>camera_link</frame_name>
      </plugin>
    </sensor>
  </gazebo>

  <gazebo>
    <pose>1 1 0.1 0 0 0</pose>
  </gazebo>

</robot>


 